[build]
  base = ""
  command = "npm ci && npm run build"
  functions = "netlify/functions"
  publish = "build"

[functions]
  node_bundler = "nft"

[[plugins]]
  package = "@xata.io/netlify"

[build.environment]
  NODE_VERSION = "18.20.6"
  NPM_VERSION = "10.8.2"
  CI = "false"