[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  functions = "netlify/functions"
  publish = "build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@xata.io/client"]


[[plugins]]
  package = "@xata.io/netlify"

[build.environment]
  NODE_VERSION = "18.20.6"
  NPM_VERSION = "9.2.0"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"